name: Daily AI News Push

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: 

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      env:
        PUSHPLUS_TOKEN: 'be1dc2dfd430433b81ecc4893e93eb68'
        AI_API_KEY: 'sk-355db06057294ffb87021e501621e0a2'
      run: |
        python main.py
